version: "3.1"
services:
  api:
    build:
      context: ../../backend/api
      dockerfile: ./Dockerfile
    restart: on-failure
    environment:
      -  STAGE_STATUS="dev"
      -  HOSTNAME="app-x1x1-xxxxx"
      -  DB_TYPE="pgx"   # pgx or mysql
      -  DB_HOST="db"
      -  DB_PORT=5432
      -  DB_USER="postgres"
      -  DB_PASSWORD="password"
      -  DB_NAME="postgres"
      -  DB_SSL_MODE="disable"
      -  DB_MAX_CONNECTIONS=100
      -  DB_MAX_IDLE_CONNECTIONS=3
      -  DB_MAX_LIFETIME_CONNECTIONS=2
      -  DB_TIMEZONE="UTC"
      -  SERVER_HOST="0.0.0.0"
      -  SERVER_PORT=5000
      -  SERVER_READ_TIMEOUT=60
    ports:
      - 5000:5000
    links:
      - db
      - etcd
  #   # command: sh -c "sleep 10;"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: cgapp-postgres
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    expose:
      - 2379 
      - 2380
    ports:
      - 2379:2379
      - 2380:2380
