version: "3.1"
services:
  # api:
  #   build:
  #     context: ../../backend/api
  #     dockerfile: ./Dockerfile
  #   restart: on-failure
  #   environment:
  #     - STAGE_STATUS="dev"
  #     - HOSTNAME="app-x1x1-xxxxx"
  #     - DB_HOST=10.5.0.5
  #     - DB_PORT=5432
  #     - DB_USER="shamir"
  #     - DB_PASSWORD="password"
  #     - DB_NAME="cgapp-postgres"
  #     - DB_SSL_MODE="disable"
  #     - DB_MAX_CONNECTIONS=100
  #     - DB_MAX_IDLE_CONNECTIONS=3
  #     - DB_MAX_LIFETIME_CONNECTIONS=2
  #     - DB_TIMEZONE="UTC"
  #     - SERVER_HOST="0.0.0.0"
  #     - SERVER_PORT=5000
  #     - SERVER_READ_TIMEOUT=60
  #     - ETCD_DSN="10.5.0.6:2379,10.5.0.6:2380"
  #   ports:
  #     - 5000:5000
  db:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: shamir
      POSTGRES_DB: cgapp-postgres
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380

